### ISSUE TITLE
Theme element in highchart API

### ISSUE THREAD

**Issue by jpimag** [thombergs/wicked-charts#37]
Since Highchart 3.0, a theme element can be added on some elements like navigation.exportButtons.
This element is not mapped in java classes.

HighChart documentation :

theme: Object
Since 3.0
A configuration object for the button theme. The object accepts SVG properties like stroke-width, stroke and fill. Tri-state button styles are supported by the states.hover and states.select objects.

**Comment by thombergs** [comment]
integrated pull request into current version
