### ISSUE TITLE
Mixed Content Error

### ISSUE THREAD

**Issue by awronski** [thombergs/wicked-charts#46]
I want to add charts to secured page (https). But there is an error:

Mixed Content: The page at 'https://example.com/DashboardPage' was loaded over HTTPS, but requested an insecure script 'http://code.highcharts.com/3.0.2/highcharts.js'. This request has been blocked; the content must be served over HTTPS.

To fix the problem it is sufficient to fix the urls from:

DEFAULT_HIGHCHARTS_URL = "http://code.highcharts.com/3.0.2/highcharts.js";
DEFAULT_HIGHCHARTS_MORE_URL = "http://code.highcharts.com/3.0.2/highcharts-more.js";
DEFAULT_HIGHCHARTS_EXPORTING_URL = "http://code.highcharts.com/3.0.2/modules/exporting.js";

to:
DEFAULT_HIGHCHARTS_URL = "//code.highcharts.com/3.0.2/highcharts.js";
DEFAULT_HIGHCHARTS_MORE_URL = "//code.highcharts.com/3.0.2/highcharts-more.js";
DEFAULT_HIGHCHARTS_EXPORTING_URL = "//code.highcharts.com/3.0.2/modules/exporting.js";

(Remove http:)

**Comment by awronski** [comment]
Workaround:

JavaScriptResourceRegistry.getInstance().setHighchartsReference("//code.highcharts.com/3.0.2/highcharts.js");

**Comment by thombergs** [comment]
This is not just a workaround, but the intended way to handle HTTPS / SSL with Wicked Charts.

Also see here: https://github.com/thombergs/wicked-charts/wiki/Feature:-Using-HTTPS

**Comment by papichulo** [comment]
The links above and in the wiki are broken.
