### ISSUE TITLE
Wicked-chart-jsf create progmaticcaly

### ISSUE THREAD

**Issue by sniperiano02** [thombergs/wicked-charts#50]

**Comment by sniperiano02** [comment]
I want to create chart from backing bean but i got null pointer exception with no details
UIChart chart = new UIChart();
		Options options = new Options();
		ChartOptions chartOptions = new ChartOptions();
	    chartOptions
	        .setType(SeriesType.LINE);
	    chartOptions
	        .setMarginRight(130);
	    chartOptions
	        .setMarginBottom(25);
	    options.setChartOptions(chartOptions);

	    Title title = new Title("Monthly Average Temperature");
	    title
	        .setX(-20);
	    options.setTitle(title);

	    Title subTitle = new Title("Source: WorldClimate.com");
	    subTitle
	        .setX(-20);
	    options.setSubtitle(subTitle);

	    com.googlecode.wickedcharts.highcharts.options.Axis xxAxis = new com.googlecode.wickedcharts.highcharts.options.Axis();
	    xxAxis
	        .setCategories(Arrays
	            .asList(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun",
	                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
	   options.setxAxis(xxAxis);

	    PlotLine plotLines = new PlotLine();
	    plotLines
	        .setValue(0f);
	    plotLines
	        .setWidth(1);
	    plotLines
	        .setColor(new HexColor("#999999"));

	    com.googlecode.wickedcharts.highcharts.options.Axis yyAxis = new com.googlecode.wickedcharts.highcharts.options.Axis();
	    yyAxis
	        .setTitle(new Title("Temperature (C)"));
	    yyAxis
	        .setPlotLines(Collections
	            .singletonList(plotLines));
	    options.setyAxis(yyAxis);

	    Legend legend = new Legend();
	    legend
	        .setLayout(LegendLayout.VERTICAL);
	    legend
	        .setAlign(HorizontalAlignment.RIGHT);
	    legend
	        .setVerticalAlign(VerticalAlignment.TOP);
	    legend
	        .setX(-10);
	    legend
	        .setY(100);
	    legend
	        .setBorderWidth(0);
	    options. setLegend(legend);

	    Series<Number> series1 = new SimpleSeries();
	    series1
	        .setName("Tokyo");
	    series1
	        .setData(Arrays
	            .asList(new Number[] { 7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5,
	                23.3, 18.3, 13.9, 9.6 }));
	    options.  addSeries(series1);

	 Grave [javax.enterprise.resource.webcontainer.jsf.context] (http--0.0.0.0-8080-3) java.lang.NullPointerException
Any Help

**Comment by hectorhzm** [comment]
Your find solve it? I have the same issue.

**Comment by sniperiano02** [comment]
I just created a List<Options> in the back bean and a <c:forEach items=#{backBean.thatList} var=opt>
<wc:chart options="#{opt}"  />

 in the xhtml and with ajax update the content where charts
