### ISSUE TITLE
Separate PlotOptions for each Series

### ISSUE THREAD

**Issue by chandrahasan** [thombergs/wicked-charts#51]
I created multi axis stacked column chart through WickedChart . 
Now I want to set "setPointPadding" for each column series . Kindly help to solve this issue

**Comment by sgautrin** [comment]
This answer is late and you most likely have found a solution by now, though this might help others, and the mechanism can apply to other not yet supported options.

Setting this option individually on a series is not supported in the last version of wicked-charts (only through `plotOptions.<type>.pointPadding`). However, you can add support for it yourself in the meantime with some code overloading. The easiest way I can think of is to add in your project a copy of the `com.googlecode.wickedcharts.highcharts.options.series.Series<D>` class (keep the package) and then upgrade it to support pointPadding. Your overloaded version being in your own project will overshadow the original class and will be the one used.

You then just have to add a Number pointPadding property to your overload with the adequate accessors.

```java
private Number pointPadding;

public Number getPointPadding() { return this.pointPadding; }

public Series<D> setPointPadding(final Number pointPadding) { this.pointPadding = pointPadding ; return this; }
```

This will let you specify the property individually for each series (but it will really have an effect only for supported types, i.e. bar, boxplot, column, columnrange, errorbar, waterfall).

You can of course contribute that to the project afterwards.

**Comment by thombergs** [comment]
Actually, pointPadding is included in the class PlotOptions since the start, so you should not really need to overload it.

**Comment by sgautrin** [comment]
@thombergs That's what I mentioned. However the original request (as far as I understood it) was to set it on each individual series, which is possible with HighCharts using by specifying it directly on the series itself, but is not however currently supported in Wicked-Charts, i.e. on the `Series<D>` class. That's why I was suggestion to overload `Series` (and not `PlotOptions`) to add it if he actually wanted to specify it on a specific series while leaving other series of the same type unaffected.

**Comment by thombergs** [comment]
Ok, I understand now. Looking at the Highcharts docs, I see that there are a couple more properties missing. I will add pointPadding, but will leave the other properties out for now (no time to add all of them).
