### ISSUE TITLE
On which maven repository can I find 1.6.0? Central only contains 1.5.0.

### ISSUE THREAD

**Issue by pblanchardie** [thombergs/wicked-charts#52]
Or, is it planned to add 1.6.0 to central?

**Comment by thombergs** [comment]
Well, it's been planned for some time, but I haven't had the time to check the quality of the build to release it so far.

Sorry, don't know when I will be able to do it.

**Comment by thombergs** [comment]
Better late than never! 2.0.0 has just been released to maven central.
