### ISSUE TITLE
Multiple Axis Wicked Charts Error

### ISSUE THREAD

**Issue by danielgonza** [thombergs/wicked-charts#54]
Hi!
I was working in a graph with multiple axis using wicked charts.
Sometimes, the graph axis have a strange behavior. The zero point is wrong.
![wickederror](https://cloud.githubusercontent.com/assets/10440804/10460448/f606c762-7199-11e5-9fd3-e61a073d1dc9.png)

Can you help please?
Thanks you

**Comment by thombergs** [comment]
Probably some configuration option is wrong. This is most likely a Highcharts issue and not a Wicked Charts issue, since Wicked charts is just a wrapper. Sorry, can't help here.
