### ISSUE TITLE
JSF 2.2 Error: Object com.googlecode.wickedcharts.Chart not found

### ISSUE THREAD

**Issue by frunk** [thombergs/wicked-charts#55]
Hi,
I'm trying to run your demo-Code (from getting started page) in a JSF 2.2 environment. I'm getting the following error when going to the page including the chart:
```
javax.faces.FacesException: Expression Error: Named Object com.googlecode.wickedcharts.Chart not found.
```
Environment: Java8, Tomcat8, Maven
Part of my pom.xml:
```xml
		<dependency>
			<groupId>com.sun.faces</groupId>
			<artifactId>jsf-api</artifactId>
			<version>2.2.12</version>
		</dependency>
		<dependency>
			<groupId>com.sun.faces</groupId>
			<artifactId>jsf-impl</artifactId>
			<version>2.2.12</version>
		</dependency>
		<dependency>
			<groupId>javax.el</groupId>
			<artifactId>javax.el-api</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>2.5</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
			<version>1.2</version>
			<scope>compile</scope>
		</dependency>


		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>primefaces</artifactId>
			<version>${primefacesVersion}</version>
		</dependency>

		<dependency>
			<groupId>com.googlecode.wicked-charts</groupId>
			<artifactId>wicked-charts-jsf21</artifactId>
			<version>1.5.0</version>
		</dependency>
```
Is the wicked-charts 1.5.0 release not compatible with JSF 2.2?

**Comment by thombergs** [comment]
Wicked Charts has only been tested with JSF 1.2, as shown in the showcase. I have no quick solution to this problem. Will keep this issue open to address this issue some time in the future.

**Comment by frunk** [comment]
I found a workaround: it works if I add the following to the faces-config.xml 

  <component>
      <component-type>com.googlecode.wickedcharts.Chart</component-type>
      <component-class>com.googlecode.wickedcharts.jsf21.UIChart</component-class>
  </component>

**Comment by thombergs** [comment]
Thanks for the tip! Added it to the Getting Started Page:
https://github.com/thombergs/wicked-charts/wiki/Getting-Started.
