### ISSUE TITLE
Wicket-charts problem in SSL mode

### ISSUE THREAD

**Issue by ryluis** [thombergs/wicked-charts#56]
hi guys,

i have just converted my application into SSL mode. But the chart image can not be rendered in the page, also i can not click any links from menu.
When i tried to remove the chart from the page class and html, everything was working fine.

I didn't see any error thrown in the logs. Did i miss something for the configuration ?

**Below is the page without SSL**
![without-ssl](https://cloud.githubusercontent.com/assets/8663945/11581851/7c1de1c0-9a79-11e5-903f-de9aeb2baeec.jpg)

**Below is the page with SSL**
![with-ssl](https://cloud.githubusercontent.com/assets/8663945/11581864/ab79b160-9a79-11e5-8d43-a8b0f895bdbe.jpg)

please kindly advise.

regards.

Arry

**Comment by martin-g** [comment]
You should use `com.googlecode.wickedcharts.wicket6.JavaScriptResourceRegistry#setHighchartsReference(java.lang.String)` to point to `https://code.highcharts.com/4.1.1/highcharts.js`. 
By default it loads from the plain/HTTP url.

**Comment by thombergs** [comment]
Probably what Martin said is the cause of your problem. You might want to use your browser's dev tools to see which resources the browser is trying to load from where. Probably your browser will give you an error like "mixed content" which says that it cannot load unsecure (http) content for a secure (https) page.

**Comment by ryluis** [comment]
Hi Martin and Tom.

Thanks for your response..i have fixed my problem.

You save my days.

-------------
Regards.

Arry
