### ISSUE TITLE
error in dependecy artifact 2.0.0 for java wrapper

### ISSUE THREAD

**Issue by lipodido** [thombergs/wicked-charts#64]
Hi
i think there is an error in maven dependecy artifact  for java wrapper 
it must be 
<dependency>
	<groupId>com.googlecode.wicked-charts</groupId>
	**<artifactId>highcharts-wrapper</artifactId>**
	<version>2.0.0</version>
</dependency>
and not (the old one )
<dependency>
  <groupId>com.googlecode.wicked-charts</groupId>
 ** <artifactId>wicked-charts-highcharts</artifactId>**
  <version>2.0.0</version>
</dependency>

**Comment by thombergs** [comment]
Fixed the error in the readme.

Thanks for the hint.
