### ISSUE TITLE
Some special characters won't work

### ISSUE THREAD

**Issue by jlaamanen** [thombergs/wicked-charts#66]
Hi,

I noticed that the Scandinavian/German characters ö & Ö (unicode 0xf6 & 0xd6) aren't supported in any titles or labels. In HighCharts they seem to work fine, but when using Wicked Charts, "Öö" is replaced with "Oo". However, characters "ÄäÅå" seem OK.

**Comment by jlaamanen** [comment]
After some research, I found out that the fix for issue #29 causes this issue; when serializing to JSON, all "turkish characters" are replaced with their original ASCII look-alikes. If #29 only causes some enum serializing to fail with Turkish locale, I'd suggest changing line 30 in class `LowercaseEnumSerializer` to something like this (and remove the method `convertTurkishChars` in `JsonRenderer` altogether):

`jgen.writeString(value.toString().toLowerCase(Locale.ENGLISH));`

Specifying the English locale will convert uppercase I to lowercase i correctly with a dot, regardless of the JVM locale.

Meanwhile, I was able to go around this issue with these steps, if someone is interested:

* Extend class `JsonRenderer` to a new class `CustomJsonRenderer`
* Override method `public String convertTurkishChars(String text)` to just return `text` as it is
* Extend class `ChartBehavior` to a new class `JsonRendererBehavior` (requires also defining a constructor with `Chart container` as argument)
* Override method `includeChartJavascript` there and ignore the `JsonRenderer renderer` given as argument, but pass your own renderer instead:

`super.includeChartJavascript(response, options, new CustomJsonRenderer(), markupId);`

* Extend class `Chart` to a new class `CustomChart`
* In the constructor of `CustomChart`, add the behavior after calling super constructor:

`add(new JsonRendererBehavior(this));`

* Use `CustomChart` instead of `Chart` when defining your charts

**Comment by thombergs** [comment]
I added the mofification you suggested. Thanks for the research!
