### ISSUE TITLE
Chart / Chart is doubled

### ISSUE THREAD

**Issue by ml007r** [thombergs/wicked-charts#68]
Hi,

i am facing a problem with your great java wrapper. The "chart" is double...so this is the code:

...
Options options = new Options();
        options.setChart(new ChartOptions().setZoomType(ZoomType.XY).setRenderTo(renderTo).setType(SeriesType.COLUMN));
...

and the result would be:

chart: {
  "chart" : {
    "renderTo" : "bla",
    "type" : "column",
    "zoomType" : "xy"
  },

produced with this code:

Options opt = MoMBarChart.createChart(context, "bla");
JsonRenderer bla = new JsonRenderer();
System.out.println("chart: " + bla.toJson(opt));

But this seems not to work - one "chart" is enough. 

Am i doing something wrong? Please advice...

BR Marcel

**Comment by thombergs** [comment]
You added the duplicate "chart:" in your System.out.println() yourself. Remove the "chart:" from your System.out.println() and it will be gone.
