### ISSUE TITLE
client side export: offline mode

### ISSUE THREAD

**Issue by dermitdemwolftanzt** [thombergs/wicked-charts#71]
Is it possible to set the client side export (offline mode) with no fall back to exporting server?
if yes, how can I do this in properly?

Thank you in advance

**Comment by thombergs** [comment]
If your question is "can I set the option [exporting.fallbackToExportServer](http://api.highcharts.com/highcharts#exporting.fallbackToExportServer) using wicked-charts?" then the answer is:

Yes, with the workaround of extending the Exporting option class as described [here](https://github.com/thombergs/wicked-charts/wiki/Feature:-Extending-Wicked-Charts).

**Comment by dermitdemwolftanzt** [comment]
Hallo Tom, 
in example you referenced there are @Override  annotations above setters/getters. What does it mean? Do I need to overwrite the ChartOptions class as well?
The other question: how could I include offline-exporting.js properly? Is it included by default? or should
I use JavaScriptResourceRegistry class? if yes, which method? Thank you in advance.

**Comment by dermitdemwolftanzt** [comment]
I have used the ExportOptions and got this set:
"exporting" : {
    "enabled" : true,
    "fallbackToExportServer" : false
  },
unfortunately it still tries to use export.highchart.com to export charts. Do you have any solutions for this? thank you in advance.

**Comment by dermitdemwolftanzt** [comment]
I'm getting this works. Need to add the offline-exporting.js by adding this in my renderHead method:
...
final JavaScriptResourceReference CHART_OFFLINE_EXPORT = new JavaScriptResourceReference(MyApplication.class, "offline-exporting.js");
response.render(JavaScriptReferenceHeaderItem.forReference(CHART_OFFLINE_EXPORT));
thank you anyway !

**Comment by thombergs** [comment]
thanks for sharing the solution!
