### ISSUE TITLE
How to use wicked-charts with Spring MVC

### ISSUE THREAD

**Issue by winterspan** [thombergs/wicked-charts#74]
I'm trying to determine what objects to use to return the appropriate JSON from a Spring MVC controller to create a Highchart...

**Comment by thombergs** [comment]
The JsonRenderer class maps a java Options object into a JSON structure that can be passed into a Highcharts javascript snippet. For Wicket and JSF, wicked-charts provides that javascript snippet (and some additional features like AJAX and the like). For Spring MVC, you would have to create that javascript snippet yourself.
