### ISSUE TITLE
Change options object and update JSF Chart

### ISSUE THREAD

**Issue by Klenkes1900** [thombergs/wicked-charts#77]
Hi, i want to change the Options Object via Backing Bean and update the chart.
At the moment, the chart widget does not support update (I call update for the parent panel but the chart displays the old data.

This is my xhtml:

```
<p:commandButton value="Update Chart" update="_chartDlg" oncomplete="PF('chartDlg').show();" action="#{bean.updateChart()}"/>

<p:dialog widgetVar="chartDlg" id="_chartDlg" header="Chart">
	<p:panelGrid layout="grid" columns="1">
		<wc:chart id="_chart1" options="#{bean.pieChartOptions}" theme="#{bean.theme}" />
	</p:panelGrid>
</p:dialog>
```

Is it possible to implement an update?

**Comment by Klenkes1900** [comment]
I've solved the problem with a little change:

In UIChart.java, i removed the CDATA Tag of the constants PRE_JS and POST_JS:

private final static String PRE_JS = "\n<script type=\"text/javascript\">\n$(function() {\n";
private final static String POST_JS = "\n;});\n</script>";

**Comment by thombergs** [comment]
Awesome. Thanks for sharing the solution!
